name: realtimekit_core_ios
description: iOS implementation of the realtimekit_core plugin
version: 0.1.3
homepage: https://docs.realtime.cloudflare.com/flutter-core

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: realtimekit_core
    platforms:
      ios:
        pluginClass: FlutterCorePlugin
        dartPluginClass: FlutterCoreIOS

dependencies:
  flutter:
    sdk: flutter
  realtimekit_core_platform_interface: ^0.1.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
